# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/EarthlingProtocol.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproto/EarthlingProtocol.proto\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0c\x45\x63hoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\rReportRequest\x12\x12\n\nreportType\x18\x01 \x01(\t\"#\n\x0eReportResponse\x12\x11\n\tidleCount\x18\x01 \x01(\x05\"A\n\x0bTaskRequest\x12\x0e\n\x06taskNo\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tqueueName\x18\x03 \x01(\t\"2\n\x0cTaskResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tidleCount\x18\x02 \x01(\x05\x32\x96\x01\n\tEarthling\x12%\n\x04\x45\x63ho\x12\x0c.EchoRequest\x1a\r.EchoResponse\"\x00\x12\x35\n\x10ReportIdleWorker\x12\x0e.ReportRequest\x1a\x0f.ReportResponse\"\x00\x12+\n\nNotifyTask\x12\x0c.TaskRequest\x1a\r.TaskResponse\"\x00\x62\x06proto3')



_ECHOREQUEST = DESCRIPTOR.message_types_by_name['EchoRequest']
_ECHORESPONSE = DESCRIPTOR.message_types_by_name['EchoResponse']
_REPORTREQUEST = DESCRIPTOR.message_types_by_name['ReportRequest']
_REPORTRESPONSE = DESCRIPTOR.message_types_by_name['ReportResponse']
_TASKREQUEST = DESCRIPTOR.message_types_by_name['TaskRequest']
_TASKRESPONSE = DESCRIPTOR.message_types_by_name['TaskResponse']
EchoRequest = _reflection.GeneratedProtocolMessageType('EchoRequest', (_message.Message,), {
  'DESCRIPTOR' : _ECHOREQUEST,
  '__module__' : 'proto.EarthlingProtocol_pb2'
  # @@protoc_insertion_point(class_scope:EchoRequest)
  })
_sym_db.RegisterMessage(EchoRequest)

EchoResponse = _reflection.GeneratedProtocolMessageType('EchoResponse', (_message.Message,), {
  'DESCRIPTOR' : _ECHORESPONSE,
  '__module__' : 'proto.EarthlingProtocol_pb2'
  # @@protoc_insertion_point(class_scope:EchoResponse)
  })
_sym_db.RegisterMessage(EchoResponse)

ReportRequest = _reflection.GeneratedProtocolMessageType('ReportRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPORTREQUEST,
  '__module__' : 'proto.EarthlingProtocol_pb2'
  # @@protoc_insertion_point(class_scope:ReportRequest)
  })
_sym_db.RegisterMessage(ReportRequest)

ReportResponse = _reflection.GeneratedProtocolMessageType('ReportResponse', (_message.Message,), {
  'DESCRIPTOR' : _REPORTRESPONSE,
  '__module__' : 'proto.EarthlingProtocol_pb2'
  # @@protoc_insertion_point(class_scope:ReportResponse)
  })
_sym_db.RegisterMessage(ReportResponse)

TaskRequest = _reflection.GeneratedProtocolMessageType('TaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _TASKREQUEST,
  '__module__' : 'proto.EarthlingProtocol_pb2'
  # @@protoc_insertion_point(class_scope:TaskRequest)
  })
_sym_db.RegisterMessage(TaskRequest)

TaskResponse = _reflection.GeneratedProtocolMessageType('TaskResponse', (_message.Message,), {
  'DESCRIPTOR' : _TASKRESPONSE,
  '__module__' : 'proto.EarthlingProtocol_pb2'
  # @@protoc_insertion_point(class_scope:TaskResponse)
  })
_sym_db.RegisterMessage(TaskResponse)

_EARTHLING = DESCRIPTOR.services_by_name['Earthling']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ECHOREQUEST._serialized_start=33
  _ECHOREQUEST._serialized_end=63
  _ECHORESPONSE._serialized_start=65
  _ECHORESPONSE._serialized_end=96
  _REPORTREQUEST._serialized_start=98
  _REPORTREQUEST._serialized_end=133
  _REPORTRESPONSE._serialized_start=135
  _REPORTRESPONSE._serialized_end=170
  _TASKREQUEST._serialized_start=172
  _TASKREQUEST._serialized_end=237
  _TASKRESPONSE._serialized_start=239
  _TASKRESPONSE._serialized_end=289
  _EARTHLING._serialized_start=292
  _EARTHLING._serialized_end=442
# @@protoc_insertion_point(module_scope)
